<a href="https://colab.research.google.com/github/kenny2408/Redes-Neuronales-con-Python-y-Keras/blob/main/dimensiones_tensores_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

***Scalar***

In [4]:
x = np.array(42)
print(x.shape)
x.ndim

()


0

***Vector***

In [5]:
x = np.array([42,3,5,3,6,7])
print(x.shape)
x.ndim

(6,)


1

***Matrix***

In [7]:
x = np.array([[42,3,5,3,6,7],
             [66,54,5,343,6,7]])
print(x.shape)
x.ndim

(2, 6)


2

***Tensor***

In [14]:
x = np.array([[[42,3,5,3,6,7],
             [66,54,5,343,6,7]],
             [[42,3,5,3,6,7],
             [66,54,5,343,6,7]],
             [[42,3,5,3,6,7],
             [66,54,5,343,6,7]]])
print(x.shape)
x.ndim

(3, 2, 6)


3

**Reshape**

In [18]:
x = np.array([[0,1],
              [2,3],
              [4,5],
              [6,7],
              [8,9]])
x.shape

(5, 2)

In [20]:
x.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [21]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.transpose(x)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [24]:
x.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])